# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl:
title: David Loher PhD
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: Social Anthropologist
author: David Loher
email: david.loher [at] posteo [dot] org
description: A Jekyll theme based on tufte-css
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Zurich
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src
# Collections
collections:
  portfolio:
    output: true
  permalik: /:collection/:path
#Plugins
plugins:
  - jekyll-seo-tag
